### PR TITLE
Fix Rocket integration

### PR DESCRIPTION
**Pull request by stankec**
Rocket's traits have changed in version 0.3.0, this pull request adjusts the existing implementation to be compatible with the latest version of the traits.

### CODE REVIEW

**Comment by theduke** [comment]
@stankec great, thanks for the PR.

The build is failing on Windows on nightly due to `ring` not compiling.

**Comment by theduke** [comment]
@stankec also could you add information about the upgrade to `CHANGELOG.md`?

If you don't get around to it, I'll bolt it on later.

**Comment by stankec** [comment]
@theduke AppVeyor may be failing due to rust-lang/rust#42422

And I couldn't find the unreleased section in the `CHANGELOG.md` file, so as to not bork thing up, I'd prefer if you (or anybody that knows what they are doing) to do it.

Sorry for the inconvenience, It's just not clear to me what to do.

**Comment by theduke** [comment]
I just added it yesterday after your PR. :P

**Comment by theduke** [comment]
@stankec the example in juniper/examples/rocket-server.rs also needs to be updated.

I need to investigate why this is not built on travis...

**Comment by stankec** [comment]
@theduke [I did update the example](https://github.com/mhallin/juniper/pull/67/files#diff-cc877c973b76bc5142fc7917bf80c981). And I run the test suite, everything passed. [I'm even running the example on my machine](https://user-images.githubusercontent.com/1655218/28744388-1782edce-7460-11e7-969c-00b3e4efb285.png).

Are you referring to the need for a better example?

**Comment by theduke** [comment]
Haha well you shouldn't review code after 3 hours of sleep. @stankec 

Sorry bout that.

**Comment by theduke** [comment]
FYI, I have just tried to build `ring` on Appveyor: https://ci.appveyor.com/project/theduke/ring/build/1.0.1

We need to investigate what the problem is, since all builds will fail on windows now.

**Comment by mhallin** [comment]
The tests are failing on Travis too, we're just ignoring failures on nightly: https://travis-ci.org/mhallin/juniper/jobs/258473732

It seems as if Rocket has removed or renamed their `testing` feature, so our integration tests need to be fixed.

As for the Ring build failure, it seems as if they're not compatible with the GCC toolchain: https://github.com/briansmith/ring and that's why it's failing. We could probably get by with disabling the Rocket integration for Windows+GCC builds.

**Comment by theduke** [comment]
@stankec as recorded in https://github.com/mhallin/juniper/issues/70, we'd like to pull out rocket and iron integrations into  `juniper_rocket` and `juniper_iron` crates.

Would handling the extraction for iron be something you are up to? 
If not, I'll do it tomorrow.

**Comment by stankec** [comment]
Pardons. I’ll be busy tomorrow until the evening. I can do it on monday for
sure.
Does that suite you?

**Comment by fbernier** [comment]
The tests are failing on nightly because this change is incomplete and the rocket tests fail. See the `The 'testing' feature was removed.` section here: https://github.com/SergioBenitez/Rocket/blob/master/CHANGELOG.md#breaking-changes

We need to replace this: https://github.com/mhallin/juniper/pull/67/files#diff-576d7531dece2e01a8a09d86ff09c869L155

Also, :+1: on creating new crates

**Comment by stankec** [comment]
Hey. This completely slipped my mind. My laptop literally caught fire on Monday morning. I'll get to it in the evening.

**Comment by theduke** [comment]
@stankec cheers!

I already started with moving the iron integration too.

Since this has a lot of overlap, I will include your commits in my branch and then do a combined merge request if that is fine with you.

**Comment by stankec** [comment]
That’s fine with me :)

**Comment by theduke** [comment]
Merged as part of https://github.com/mhallin/juniper/pull/73

**Pull request closed without merging**
